services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
    networks:
      - local-dev-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - ./frontend/.env:/app/.env
    networks:
      - local-dev-net

networks:
  local-dev-net:
    external: true

volumes:
  frontend_node_modules:
